name: Lint

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    name: StandardRB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - run: bundle install --jobs 4 --retry 3
      - run: bundle exec standardrb
