name: Rspec

on:
  push:
    branches:
      - '**'

jobs:
  tests:
    name: all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.3', '3.2', '3.1']
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - run: bundle install --jobs 4 --retry 3
      - run: bundle exec rspec spec
